project:
  type: website
  output-dir: docs

website:
  title: "Mi primer blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/vseguro/Blog
      - icon: linkedin
        href: www.linkedin.com/in/veronica-seguro
        
format:
  html:
    theme:
      light: pulse
      dark: darkly
    css: styles.css

editor: visual

